### ISSUE TITLE
Alternative Koa-like framework.

### ISSUE THREAD

**Issue by DylanPiercey** [mlrawlings/koa-client#1]
Hey,

Almost two years ago this library inspired me to create a totally isomorphic framework and showed me how close something like Koa was to being that.

I have been working creating [Rill](https://github.com/rill-js/rill) which is a framework similar to Koa but works perfectly in the browser and supports all major features you would expect in a browser or a server side framework. You can checkout the list of middleware [here](https://github.com/rill-js/rill/wiki).

Rill is built from top to bottom with isomorphic javascript in mind. In fact Rill itself runs 100% in node and the browser thanks to [@rill/http](https://github.com/rill-js/http) which brings nodes [HTTP.createServer](https://nodejs.org/api/http.html#http_http_createserver_requestlistener) to the browser.

Just thought you might find it interesting.
If you'd like to chat about it feel free to hit me up on [gitter](https://gitter.im/rill-js/rill).

Feel free to close this issue 😄 and thanks for your work on this project.

**Comment by mlrawlings** [comment]
Hey!  Thanks for being persistent in reaching out to me.  I know you sent me an email 9 months ago and I never responded...

I need to dig into Rill a bit more, but I think this idea of a server that runs on both the server and the client is a neat idea, and one I still like.  I did end up using kent (built on koa/koa-client) for a project and I think it worked really well.  

Since I'm not actively maintaining this project, I've added a link to Rill in the README.  I'd love to talk more about some of this stuff at some point.

**Comment by DylanPiercey** [comment]
@mlrawlings thanks for getting back to me.

I have found to idea to work extremely well, I have built ~15 smallish scale websites and a few large apps with it and have had much less problems than the angular/react(flux) solutions I was using before.

If you wan't to chat about Rill i'm always available on [gitter](https://gitter.im/rill-js/rill) and if you do decide to dig into it a bit any feedback would be awesome. It has been stable for the past year or so but I have been actively reviewing the code and building [middleware](https://github.com/rill-js/rill/wiki).

Thanks for adding Rill to the README of this project, if you decide to hop back in on the idea I hope you give it a whirl. I'd love to hear about any issues you have using the project as I am always looking for ways to make it more user friendly.
